name: chequeproject
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5-153.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  http: ^0.13.5
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  file_picker: ^5.2.5
  rflutter_alert: ^2.0.7
  lottie: ^2.3.0
  syncfusion_flutter_datepicker: ^21.1.37
  flutter_swipe_action_cell: ^3.1.0
  flutter_charts: ^0.5.1
  charts_flutter: ^0.12.0
  shared_preferences: ^2.1.1
  gap: ^2.0.2
  flutter_local_notifications: ^14.1.1
  socket_io_client: ^2.0.2
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo1.png
    - assets/loader.json
    - assets/json/config.json


  
